version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - "/dev:/dev"
      # - ~/.Xauthority:/root/.Xauthority
      # - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ".:/workdir:rw"
    # environment:
    #   DISPLAY: $DISPLAY
    #   QT_X11_NO_MITSHM: 1
    network_mode: host
    privileged: true
    working_dir: /workdir
    entrypoint: "python3 app.py"


